# Generated by Django 6.0.6 on 2026-06-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_load_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(verbose_name='Fecha/Hora')),
                ('raw_data', models.TextField(blank=True, verbose_name='Línea original')),
                ('device_sn', models.CharField(blank=True, max_length=50, verbose_name='Serial del dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido el')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['employee', 'scanned_at'], name='attendance__employe_a8708d_idx')],
            },
        ),
    ]
