# Generated by Django 6.0.6 on 2026-06-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanrecord',
            new_name='registros_a_employe_2ddde8_idx',
            old_name='attendance__employe_a8708d_idx',
        ),
        migrations.AlterModelTable(
            name='scanrecord',
            table='registros_acceso',
        ),
    ]
