# Generated by Django 6.0.6 on 2026-06-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_load_employees'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='empleados',
        ),
    ]
